# Generated by Django 4.0.2 on 2022-02-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_staff_comment_profile'),
        ('device', '0002_delete_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Not delivered'), (2, 'ready to go'), (3, 'Idle'), (4, 'Wait for the upgrade'), (5, 'Wait for repairs'), (6, 'Other')], default=1)),
                ('serialNumber', models.CharField(default='Please change it after delivery', max_length=40)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.pc')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile')),
            ],
        ),
    ]
