# Generated by Django 4.0.2 on 2022-02-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_staff_comment_profile'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Nothing'), (2, 'Not complete'), (3, 'Complete')], default=1)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='serialNumber',
            field=models.CharField(default='Please change it after delivery', max_length=50),
        ),
        migrations.CreateModel(
            name='Retired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Idle'), (2, 'Recycling'), (3, 'Other')], default=1)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='step.inuse')),
            ],
        ),
        migrations.CreateModel(
            name='Preparing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=25, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Nothing'), (2, 'Not complete'), (3, 'Complete')], default=1)),
                ('comment', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='step.warehouse')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='inuse',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='step.preparing'),
        ),
        migrations.AddField(
            model_name='inuse',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile'),
        ),
        migrations.AddField(
            model_name='inuse',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.staff'),
        ),
    ]
