# Generated by Django 4.0.2 on 2022-03-07 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('step', '0003_alter_warehouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='orderer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
