# Generated by Django 4.0.2 on 2022-02-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_staff_comment_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.BooleanField()),
            ],
        ),
    ]
