# Generated by Django 4.0.2 on 2022-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
