# Generated by Django 4.0.2 on 2022-02-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Vga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vga', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Laptop'), (2, 'NUC'), (3, 'Server'), (4, 'PC'), (5, 'All-in-One'), (6, 'Other')])),
                ('storage', models.CharField(max_length=50)),
                ('display', models.CharField(blank=True, max_length=50)),
                ('other', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.brand')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.cpu')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.os')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.ram')),
                ('vga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.vga')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('other', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.brand')),
            ],
        ),
    ]
